In [3]:
import numpy as np

In [6]:
arr = np.array([[1,2,3],
               [4,5,6]])

print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


In [8]:
print(arr[arr < 6])

[1 2 3 4 5]


In [9]:
np.where(arr > 5,1,0)

array([[0, 0, 0],
       [0, 0, 1]])

In [11]:
arr

array([[1, 2, 3],
       [4, 5, 6]])